[package]
name = "libcdio-cli"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Utilities to work with CD/DVD media, ISO 9660 and UDF images"
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["cargo", "derive"] }
libcdio-rs = { path = "../libcdio-rs" }
time = { workspace = true, features = ["formatting", "local-offset", "macros"], optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# TODO: Remove the "-rs" suffixes before release
[[bin]]
name = "cd-drive-rs"
path = "src/cd-drive/main.rs"
required-features = ["cd-drive"]

[[bin]]
name = "iso-info-rs"
path = "src/iso-info/main.rs"
required-features = ["iso-info"]

[[bin]]
name = "iso-read-rs"
path = "src/iso-read/main.rs"
required-features = ["iso-read"]

[[bin]]
name = "mmc-tool-rs"
path = "src/mmc-tool/main.rs"
required-features = ["mmc-tool"]

[features]
default = ["cd-drive", "iso-info", "iso-read", "mmc-tool"]
cd-drive = ["libcdio-rs/mmc"]
iso-info = ["libcdio-rs/iso9660", "libcdio-rs/udf", "dep:time"]
iso-read = ["libcdio-rs/iso9660", "libcdio-rs/udf"]
mmc-tool = ["libcdio-rs/mmc"]

[dev-dependencies]
assert_cmd = { version = "2.2.2", features = ["color"] }
assert_fs = { version = "1.1.4", features = ["color"] }
