name: libcdio-rs CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - run: cargo test --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-features --all-targets -- -D warnings

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
    - run: cargo install cargo-msrv
    - run: cargo msrv verify
